apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Define sources first
  - ../../sources
  # Define namespaces then
  - ./namespaces
  # Define deployed applications
  - ../../base/victoriametrics-operator
  - ../../base/kube-prometheus-operator
  - ../../base/local-path-provisioner
  - ../../base/calico
  - ../../base/nginx-ingress
  - ../../base/metrics-server
  - ../../base/cert-manager-crds
  - ../../base/local-path-provisioner-regular
  - ../../base/local-path-provisioner-fast
  - ../../base/postgres-operator
#  - ../../base/minio-operator
#  - ../../base/minio-tenant
#  - ../../base/longhorn
  - ../../base/velero
  - ../../base/tigera-operator
  - ../../base/nvidia-device-plugin
  - ../../base/volcano
  - ../../base/gpu-operator
  - ../../base/matomo
#  - ../../base/kai-scheduler
  - ./resource-quota
  - ./limit-range

patchesStrategicMerge:
  - victoriametrics-operator/release.yaml
  - kube-prometheus-operator/prometheus-operator-deployment.yaml
  - local-path-provisioner/configmap.yaml
  - local-path-provisioner/deployment.yaml
  - nginx-ingress/release.yaml
  - local-path-provisioner-regular/configmap.yaml
  - local-path-provisioner-regular/deployment.yaml
  - local-path-provisioner-fast/configmap.yaml
  - local-path-provisioner-fast/deployment.yaml
  - local-path-provisioner-fast/storageclass.yaml
